### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by traversaro** [cbeck88/visit_struct#25]
First of all, thaks a lot @garbageslam for the great library. 

I was wondering if you were interesting in releasing a new version of the library, bumping the version in https://github.com/garbageslam/visit_struct/blob/8c91d2283c7050593df5b692a13cb0ea99ba81d5/include/visit_struct/visit_struct.hpp#L18 and creating a new tag? The current master contains some new features w.r.t. to the v1.0.0 release, and it would be great to have a release explicitly containing this new features. 

Thanks a lot in advance.

**Comment by traversaro** [comment]
To give a bit more of context, the benefit of a new release is that users that install `visit_struct` via conan or vcpkg (see https://repology.org/project/visit-struct/versions) can be benefit from the new features.

**Comment by cbeck88** [comment]
Yes let's do this, thanks for your interest! Im glad this library is useful to people

**Comment by traversaro** [comment]
> Yes let's do this, thanks for your interest! Im glad this library is useful to people

Thanks a lot for merging! Yes we use extensively this library in the context of logging time series arbitrary C++ structures on files, see https://github.com/robotology/robometry#example-multiple-types and https://github.com/ami-iit/matio-cpp#example-of-usage .

Can you also add a tag `v1.1` that points to the latest master commit? For updating visit_struct packages in package managers such as vcpkg ( https://github.com/microsoft/vcpkg/blob/501db0f17ef6df184fcdbfbe0f87cde2313b6ab1/ports/visit-struct/portfile.cmake#L5 ) or conda-forge (https://github.com/conda-forge/visit_struct-feedstock/blob/89d45c568892ae8ce55956f83d13e5a402c6e6e1/recipe/meta.yaml#L9) it is easier if there is a tag, so that it is clear to everyone and unambigous which commit refer to a given release. Thanks a lot in advance @cbeck88 !

**Comment by cbeck88** [comment]
Yes absolutely

**Comment by cbeck88** [comment]
okay should be done now

---

I didn't realize the extent to which this library is being used. Thank you! I will take some time to go through the backlog of issues and try to help with the packaging issues. Maybe I will try to find a comaintainer also

**Comment by traversaro** [comment]
Thanks a lot!

> I didn't realize the extent to which this library is being used. Thank you! I will take some time to go through the backlog of issues and try to help with the packaging issues. Maybe I will try to find a comaintainer also

If you need any help feel free to ask, thanks!
